# Generated by Django 4.1.4 on 2025-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_manager_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='html_block',
            field=models.TextField(default='', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.ImageField(default='aboba', upload_to='managers/'),
        ),
    ]
