# Generated by Django 4.1.4 on 2025-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(verbose_name='ФИО')),
                ('image', models.ImageField(default='aboba', upload_to='managers/')),
                ('html_block', models.TextField(default='', verbose_name='Код')),
            ],
        ),
    ]
