# Generated by Django 4.1.4 on 2025-05-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='html_block',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='image',
        ),
        migrations.AddField(
            model_name='calc',
            name='a',
            field=models.IntegerField(default='4'),
        ),
        migrations.AddField(
            model_name='calc',
            name='x',
            field=models.IntegerField(default='3'),
        ),
    ]
