# Generated by Django 4.1.4 on 2025-05-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0002_remove_calc_fio_remove_calc_html_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='a',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='x',
            field=models.IntegerField(default='0'),
        ),
    ]
