# Generated by Django 4.1.4 on 2025-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0004_alter_calc_a_alter_calc_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calc',
            name='x',
            field=models.IntegerField(),
        ),
    ]
