# Generated by Django 4.1.4 on 2025-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0005_alter_calc_a_alter_calc_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calc',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
